# **Covariance Matrix**

In [35]:
import numpy as np

## **Dataset**

We have $n$ data points, where each point contains two features: $x$ and $y$.

In [36]:
A = np.array([
    [10, 5],
    [12, 3],
    [6, 9],
    [6, 4],
    [5, 11],
    [14, 2],
    [8, 1],
    [3, 13]
])
n = len(A)

In [37]:
A

array([[10,  5],
       [12,  3],
       [ 6,  9],
       [ 6,  4],
       [ 5, 11],
       [14,  2],
       [ 8,  1],
       [ 3, 13]])

## **Mean**

We will calculate the mean of $x$ and $y$ using the following formula.

$$
\mu = \frac{1}{n}\sum_{i=1}^{n} x_i
$$

In [38]:
m_x = np.mean(A[:,0])
m_y = np.mean(A[:,1])

## **Mean Centering**

We subtract the mean from each data point to center the data around zero.

$$
A_m = A - \mu
$$

In [44]:
A_m = A - np.array([[m_x, m_y] for _ in range(n)])

In [45]:
A_m

array([[ 2., -1.],
       [ 4., -3.],
       [-2.,  3.],
       [-2., -2.],
       [-3.,  5.],
       [ 6., -4.],
       [ 0., -5.],
       [-5.,  7.]])

## **Covariance Matrix**

We calculate the covariance matrix using the centered data.

$$
C = \frac{1}{n-1}(A-\mu)^T(A-\mu)
$$

In [49]:
cov_matrix = (np.transpose(A_m) @ A_m) / (n-1)

In [50]:
cov_matrix

array([[ 14.        , -12.85714286],
       [-12.85714286,  19.71428571]])

# **Covariance Matrix** - Dynamic Solution

In [52]:
A = np.array([
    [10, 5],
    [12, 3],
    [6, 9],
    [6, 4],
    [5, 11],
    [14, 2],
    [8, 1],
    [3, 13]
])
n = len(A)

In [57]:
def compute_mean_matrix(A):
    mean = []
    for i in range(len(A[0])):
        mean.append(np.mean(A[:,i]))
    return np.array([mean for _ in range(n)])

In [62]:
def convariance_matrix(A):
    mean_matrix = compute_mean_matrix(A)
    A_m = A - mean_matrix
    return (np.transpose(A_m) @ A_m) / (n-1)

In [63]:
convariance_matrix(A)

array([[ 14.        , -12.85714286],
       [-12.85714286,  19.71428571]])