# **Gauss-Jordan Elimination**
Implement this **from scratch with NumPy**:

$$
\begin{aligned}
2x + y - z &= 8\\
-3x - y + 2z &= -11\\
-2x + y + 2z &= -3
\end{aligned}
$$



In [96]:
A = np.array([
    [2, 1, -1],
    [-3, -1, 2],
    [-2, 1, 2]
])

b = np.array([8, -11, -3])

In [97]:
A,b

(array([[ 2,  1, -1],
        [-3, -1,  2],
        [-2,  1,  2]]),
 array([  8, -11,  -3]))

In [99]:
def gaussian_elimination(A, b):
    mat = np.hstack((A, b.reshape(-1,1)), dtype=np.float64)

    def eliminate(pivot_index):
        for index, row in enumerate(mat):
            if index == pivot_index:
                continue
            multiplier = row[pivot_index]
            row = row - (mat[pivot_index] * multiplier)
            mat[index] = row

    for i in range(len(mat)):
        if mat[i][i] == 0:
            for j in range(i + 1, len(mat)):
                if mat[j][i] != 0:
                    mat[i], mat[j] = mat[j].copy(), mat[i].copy() 
                    break
        pivot_element = mat[i][i]
        if pivot_element == 0:
            continue

        mat[i] = mat[i] / pivot_element

        eliminate(i)
    return mat
gaussian_elimination(A, b)

array([[ 1.,  0.,  0.,  2.],
       [ 0.,  1.,  0.,  3.],
       [-0., -0.,  1., -1.]])