# **Implementing PCA using Numpy**

In [44]:
import numpy as np

#### 1. Helper function to create mean matrix

In [45]:
def compute_mean_matrix(A):
    mean = []
    n = len(A)
    for i in range(len(A[0])):
        mean.append(np.mean(A[:,i]))
    return np.array([mean for _ in range(n)])

#### 2. Helper function to create covariance matrix

In [46]:
def convariance_matrix(A):
    n = len(A)    
    mean_matrix = compute_mean_matrix(A)
    A_m = A - mean_matrix
    return (np.transpose(A_m) @ A_m) / (n-1)

#### 3. Dataset

In [47]:
X = np.array([
    [2, 4, 1, 5, 3],
    [3, 6, 2, 7, 4],
    [4, 8, 3, 9, 5],
    [5, 10, 4, 11, 6],
    [6, 12, 5, 13, 7]
], dtype=float)

#### 4. Create Covariance Matrix

In [48]:
cov_matrix = convariance_matrix(X)

In [80]:
cov_matrix

array([[ 2.5,  5. ,  2.5,  5. ,  2.5],
       [ 5. , 10. ,  5. , 10. ,  5. ],
       [ 2.5,  5. ,  2.5,  5. ,  2.5],
       [ 5. , 10. ,  5. , 10. ,  5. ],
       [ 2.5,  5. ,  2.5,  5. ,  2.5]])

#### 5. Find eigen values and eigen vectors

In [50]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

#### 6. Sort the eigen vectors by eigen values

In [51]:
indices = np.argsort(eigenvalues)[::-1]

eigenvalues = eigenvalues[indices]
eigenvectors = eigenvectors[:, indices]

In [52]:
eigenvalues, eigenvectors

(array([27.5,  0. ,  0. ,  0. ,  0. ]),
 array([[ 3.01511345e-01,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00, -9.53462589e-01],
        [ 6.03022689e-01,  4.53097430e-17,  1.35929229e-16,
          7.74596669e-01,  1.90692518e-01],
        [ 3.01511345e-01, -4.08248290e-01, -8.16496581e-01,
         -2.58198890e-01,  9.53462589e-02],
        [ 6.03022689e-01, -2.36700684e-01,  5.26598632e-01,
         -5.16397779e-01,  1.90692518e-01],
        [ 3.01511345e-01,  8.81649658e-01, -2.36700684e-01,
         -2.58198890e-01,  9.53462589e-02]]))

#### 7. Choose top `k` dimension for reduction

In [53]:
k = 2

In [54]:
V = eigenvectors[:, :k]

In [55]:
V.shape

(5, 2)

#### 8. Project the centered data on to the projection matrix

In [56]:
Xpca = (X - compute_mean_matrix(X)) @ V

In [57]:
Xpca

array([[-6.63324958,  0.        ],
       [-3.31662479,  0.        ],
       [ 0.        ,  0.        ],
       [ 3.31662479,  0.        ],
       [ 6.63324958,  0.        ]])

In [58]:
Xpca.shape

(5, 2)

## **Compiled Function for performing PCA**

In [81]:
def pca(A, k):
    cov_mat = convariance_matrix(A)
    eigenvalues, eigenvectors = np.linalg.eig(cov_mat)

    indices = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[indices]
    eigenvectors = eigenvectors[:, indices]

    V = eigenvectors[:, :k]
    return (A - compute_mean_matrix(A)) @ V

In [82]:
pca(X, 1)

array([[-6.63324958],
       [-3.31662479],
       [ 0.        ],
       [ 3.31662479],
       [ 6.63324958]])